project_id = "pccvvqmrwbcdjgkyteqn"

[functions.chat]
verify_jwt = true

[functions.sync-google-calendar]
verify_jwt = true

[functions.google-drive]
verify_jwt = true

[functions.google-oauth]
verify_jwt = false

[functions.google-calendar]
verify_jwt = true

[functions.slack-webhook]
verify_jwt = false

[functions.task-notifications]
verify_jwt = false

[functions.crm-webhook]
verify_jwt = false

[functions.seventime-sync]
verify_jwt = true