project_id = "pccvvqmrwbcdjgkyteqn"

[functions.chat]
verify_jwt = true

[functions.sync-google-calendar]
verify_jwt = true

[functions.google-drive]
verify_jwt = true

[functions.google-oauth]
verify_jwt = false
